//
// Created by stuka on 22.05.2023.
//

#pragma once

#ifndef SUNGEARENGINE_GRAPHICSDATATYPES_H
#define SUNGEARENGINE_GRAPHICSDATATYPES_H

enum SGGDataType
{
    SGG_DATA_TYPE_NONE,

    SGG_DATA_TYPE_INT,
    SGG_DATA_TYPE_INT2,
    SGG_DATA_TYPE_INT3,
    SGG_DATA_TYPE_INT4,

    SGG_DATA_TYPE_FLOAT,
    SGG_DATA_TYPE_FLOAT2,
    SGG_DATA_TYPE_FLOAT3,
    SGG_DATA_TYPE_FLOAT4,

    SGG_DATA_TYPE_MAT2,
    SGG_DATA_TYPE_MAT3,
    SGG_DATA_TYPE_MAT4,

    SGG_DATA_TYPE_BOOL,
};

enum SGGBufferUsage
{
    SGG_BUFFER_USAGE_DYNAMIC,
    SGG_BUFFER_USAGE_STATIC
};

#endif //SUNGEARENGINE_GRAPHICSDATATYPES_H
