//
// Created by Ilya on 22.07.2024.
//

#ifndef SUNGEARENGINEEDITOR_TOOLCHAINSSETTINGSCONTENT_H
#define SUNGEARENGINEEDITOR_TOOLCHAINSSETTINGSCONTENT_H


class ToolchainsSettingsContent
{

};


#endif //SUNGEARENGINEEDITOR_TOOLCHAINSSETTINGSCONTENT_H
