var hierarchy =
[
    [ "SGCore::AssetManager", "classSGCore_1_1AssetManager.html", null ],
    [ "SGCore::Atmosphere", "structSGCore_1_1Atmosphere.html", null ],
    [ "SGCore::AtmosphereUtils", "structSGCore_1_1AtmosphereUtils.html", null ],
    [ "SGCore::AudioBuffer", "structSGCore_1_1AudioBuffer.html", null ],
    [ "SGCore::AudioDevice", "structSGCore_1_1AudioDevice.html", null ],
    [ "SGCore::AudioListener", "structSGCore_1_1AudioListener.html", null ],
    [ "SGCore::AudioSource", "structSGCore_1_1AudioSource.html", null ],
    [ "SGCore::AudioTrack", "structSGCore_1_1AudioTrack.html", null ],
    [ "siv::BasicPerlinNoise< Float >", "classsiv_1_1BasicPerlinNoise.html", null ],
    [ "SGCore::Batch", "structSGCore_1_1Batch.html", null ],
    [ "SGCore::BatchEntityRanges", "structSGCore_1_1BatchEntityRanges.html", null ],
    [ "SGCore::BatchingTarget", "structSGCore_1_1BatchingTarget.html", null ],
    [ "SGCore::BoxGizmo", "structSGCore_1_1BoxGizmo.html", null ],
    [ "btIDebugDraw", null, [
      [ "SGCore::PhysicsDebugDraw", "structSGCore_1_1PhysicsDebugDraw.html", null ]
    ] ],
    [ "SGCore::Camera3D", "classSGCore_1_1Camera3D.html", null ],
    [ "SGCore::class_function_traits< typename >", "structSGCore_1_1class__function__traits.html", null ],
    [ "SGCore::class_function_traits< Return(Object::*)(Args...) const >", "structSGCore_1_1class__function__traits_3_01Return_07Object_1_1_5_08_07Args_8_8_8_08_01const_01_4.html", null ],
    [ "SGCore::class_function_traits< Return(Object::*)(Args...)>", "structSGCore_1_1class__function__traits_3_01Return_07Object_1_1_5_08_07Args_8_8_8_08_4.html", null ],
    [ "SGConsole::Console", "classSGConsole_1_1Console.html", null ],
    [ "SGConsole::ConsoleEntryPoint", "classSGConsole_1_1ConsoleEntryPoint.html", null ],
    [ "SGCore::ConstexprObject< Obj >", "structSGCore_1_1ConstexprObject.html", null ],
    [ "SGCore::Controllable3D", "structSGCore_1_1Controllable3D.html", null ],
    [ "SGCore::CoreMain", "classSGCore_1_1CoreMain.html", null ],
    [ "ddsktx_error", "structddsktx__error.html", null ],
    [ "ddsktx_sub_data", "structddsktx__sub__data.html", null ],
    [ "ddsktx_texture_info", "structddsktx__texture__info.html", null ],
    [ "SGCore::DefaultShadersPaths", "structSGCore_1_1DefaultShadersPaths.html", null ],
    [ "SGCore::DeviceGLInfo", "structSGCore_1_1DeviceGLInfo.html", null ],
    [ "Dimensions< T >", "structDimensions.html", null ],
    [ "SGCore::DirectionalLight", "structSGCore_1_1DirectionalLight.html", null ],
    [ "SGCore::DisableMeshGeometryPass", "structSGCore_1_1DisableMeshGeometryPass.html", null ],
    [ "SGCore::DynamicLibrary", "structSGCore_1_1DynamicLibrary.html", null ],
    [ "std::enable_shared_from_this", null, [
      [ "SGCore::IParallelSystem< PhysicsWorld3D >", "classSGCore_1_1IParallelSystem.html", [
        [ "SGCore::PhysicsWorld3D", "structSGCore_1_1PhysicsWorld3D.html", null ]
      ] ],
      [ "SGCore::IParallelSystem< TransformationsUpdater >", "classSGCore_1_1IParallelSystem.html", [
        [ "SGCore::TransformationsUpdater", "structSGCore_1_1TransformationsUpdater.html", null ]
      ] ],
      [ "SGCore::IParallelSystem< OctreesSolver >", "classSGCore_1_1IParallelSystem.html", [
        [ "SGCore::OctreesSolver", "classSGCore_1_1OctreesSolver.html", null ]
      ] ],
      [ "SGCore::FontSpecialization", "structSGCore_1_1FontSpecialization.html", null ],
      [ "SGCore::IFrameBuffer", "classSGCore_1_1IFrameBuffer.html", [
        [ "SGCore::GL4FrameBuffer", "classSGCore_1_1GL4FrameBuffer.html", [
          [ "SGCore::GL46FrameBuffer", "classSGCore_1_1GL46FrameBuffer.html", null ]
        ] ],
        [ "SGCore::VkFrameBuffer", "classSGCore_1_1VkFrameBuffer.html", null ]
      ] ],
      [ "SGCore::IIndexBuffer", "classSGCore_1_1IIndexBuffer.html", [
        [ "SGCore::GLIndexBuffer", "classSGCore_1_1GLIndexBuffer.html", null ],
        [ "SGCore::VkIndexBuffer", "classSGCore_1_1VkIndexBuffer.html", null ]
      ] ],
      [ "SGCore::IMaterial", "classSGCore_1_1IMaterial.html", null ],
      [ "SGCore::IMeshData", "classSGCore_1_1IMeshData.html", [
        [ "SGCore::GL3MeshData", "classSGCore_1_1GL3MeshData.html", null ],
        [ "SGCore::VkMeshData", "classSGCore_1_1VkMeshData.html", null ]
      ] ],
      [ "SGCore::IParallelSystem< ParallelSystemT >", "classSGCore_1_1IParallelSystem.html", null ],
      [ "SGCore::IRenderPipeline", "structSGCore_1_1IRenderPipeline.html", [
        [ "SGCore::LWRenderPipeline", "structSGCore_1_1LWRenderPipeline.html", null ],
        [ "SGCore::PBRRenderPipeline", "structSGCore_1_1PBRRenderPipeline.html", null ]
      ] ],
      [ "SGCore::ISubPassShader", "classSGCore_1_1ISubPassShader.html", [
        [ "SGCore::GL46SubPassShader", "classSGCore_1_1GL46SubPassShader.html", null ],
        [ "SGCore::VkSubPassShader", "classSGCore_1_1VkSubPassShader.html", null ]
      ] ],
      [ "SGCore::ITexture2D", "classSGCore_1_1ITexture2D.html", [
        [ "SGCore::GL4Texture2D", "classSGCore_1_1GL4Texture2D.html", [
          [ "SGCore::GL46Texture2D", "classSGCore_1_1GL46Texture2D.html", null ]
        ] ],
        [ "SGCore::ICubemapTexture", "structSGCore_1_1ICubemapTexture.html", [
          [ "SGCore::GL4CubemapTexture", "classSGCore_1_1GL4CubemapTexture.html", null ],
          [ "SGCore::VkCubemapTexture", "classSGCore_1_1VkCubemapTexture.html", null ]
        ] ],
        [ "SGCore::VkTexture2D", "classSGCore_1_1VkTexture2D.html", null ]
      ] ],
      [ "SGCore::IUniformBuffer", "classSGCore_1_1IUniformBuffer.html", [
        [ "SGCore::GL46UniformBuffer", "classSGCore_1_1GL46UniformBuffer.html", null ],
        [ "SGCore::GL4UniformBuffer", "classSGCore_1_1GL4UniformBuffer.html", null ],
        [ "SGCore::VkUniformBuffer", "classSGCore_1_1VkUniformBuffer.html", null ]
      ] ],
      [ "SGCore::IVertexArray", "classSGCore_1_1IVertexArray.html", [
        [ "SGCore::GLVertexArray", "classSGCore_1_1GLVertexArray.html", null ],
        [ "SGCore::VkVertexArray", "classSGCore_1_1VkVertexArray.html", null ]
      ] ],
      [ "SGCore::IVertexBuffer", "classSGCore_1_1IVertexBuffer.html", [
        [ "SGCore::GLVertexBuffer", "classSGCore_1_1GLVertexBuffer.html", null ],
        [ "SGCore::VkVertexBuffer", "classSGCore_1_1VkVertexBuffer.html", null ]
      ] ],
      [ "SGCore::IVertexBufferLayout", "classSGCore_1_1IVertexBufferLayout.html", [
        [ "SGCore::GLVertexBufferLayout", "classSGCore_1_1GLVertexBufferLayout.html", null ],
        [ "SGCore::VkVertexBufferLayout", "classSGCore_1_1VkVertexBufferLayout.html", null ]
      ] ],
      [ "SGCore::ImGuiWrap::IView", "structSGCore_1_1ImGuiWrap_1_1IView.html", [
        [ "SGCore::ImGuiWrap::CollapsingHeader", "structSGCore_1_1ImGuiWrap_1_1CollapsingHeader.html", null ],
        [ "SGCore::ImGuiWrap::Window", "structSGCore_1_1ImGuiWrap_1_1Window.html", null ]
      ] ],
      [ "SGCore::InputListener", "classSGCore_1_1InputListener.html", null ],
      [ "SGCore::PostProcessLayer", "structSGCore_1_1PostProcessLayer.html", null ],
      [ "SGCore::Scene", "classSGCore_1_1Scene.html", null ],
      [ "SGCore::ShaderAnalyzedFile", "structSGCore_1_1ShaderAnalyzedFile.html", null ],
      [ "SGCore::Threading::Task", "structSGCore_1_1Threading_1_1Task.html", null ],
      [ "SGCore::Threading::Thread", "structSGCore_1_1Threading_1_1Thread.html", [
        [ "SGCore::Threading::MainThread", "structSGCore_1_1Threading_1_1MainThread.html", null ]
      ] ],
      [ "SGCore::UniqueNamesManager", "classSGCore_1_1UniqueNamesManager.html", null ]
    ] ],
    [ "SGCore::EntitiesPool", "structSGCore_1_1EntitiesPool.html", null ],
    [ "SGCore::EntityComponentMember< T >", "structSGCore_1_1EntityComponentMember.html", null ],
    [ "SGCore::Event< Return >", "structSGCore_1_1Event.html", null ],
    [ "SGCore::Event< Return(Args...)>", "structSGCore_1_1Event_3_01Return_07Args_8_8_8_08_4.html", null ],
    [ "SGCore::Event< void()>", "structSGCore_1_1Event.html", null ],
    [ "SGCore::Event< void(bool lastActive, bool isActive)>", "structSGCore_1_1Event.html", null ],
    [ "SGCore::Event< void(const double &, const double &)>", "structSGCore_1_1Event.html", null ],
    [ "SGCore::Event< void(const Ref< registry_t > &registry, const entity_t &, Ref< const SGCore::Transform >)>", "structSGCore_1_1Event.html", null ],
    [ "SGCore::Event< void(const std::string &newName)>", "structSGCore_1_1Event.html", null ],
    [ "SGCore::Event< void(SGCore::AudioSource &source, AudioSourceState lastState, AudioSourceState newState)>", "structSGCore_1_1Event.html", null ],
    [ "SGCore::Event< void(SGCore::IAsset *asset)>", "structSGCore_1_1Event.html", null ],
    [ "SGCore::Event< void(SGCore::Window &)>", "structSGCore_1_1Event.html", null ],
    [ "SGCore::Event< void(SGCore::Window &, const double &, const double &)>", "structSGCore_1_1Event.html", null ],
    [ "SGCore::Event< void(SGCore::Window &, const int &)>", "structSGCore_1_1Event.html", null ],
    [ "SGCore::Event< void(SGCore::Window &, const KeyboardKey &, const int &, const KeyState &, const int &)>", "structSGCore_1_1Event.html", null ],
    [ "SGCore::Event< void(SGCore::Window &, const MouseButton &, const KeyState &, const int &)>", "structSGCore_1_1Event.html", null ],
    [ "SGCore::EventListener< Return >", "structSGCore_1_1EventListener.html", null ],
    [ "SGCore::EventListener< Return(Args...)>", "structSGCore_1_1EventListener_3_01Return_07Args_8_8_8_08_4.html", null ],
    [ "SGCore::EventListener< void()>", "structSGCore_1_1EventListener.html", null ],
    [ "SGCore::EventListener< void(const double &, const double &)>", "structSGCore_1_1EventListener.html", null ],
    [ "SGCore::EventListener< void(const Ref< registry_t > &, const entity_t &, Ref< const SGCore::Transform >)>", "structSGCore_1_1EventListener.html", null ],
    [ "SGCore::EventListener< void(const Ref< registry_t > &registry, const entity_t &, Ref< const SGCore::Transform >)>", "structSGCore_1_1EventListener.html", null ],
    [ "SGCore::EventListener< void(const std::string &)>", "structSGCore_1_1EventListener.html", null ],
    [ "std::exception", null, [
      [ "FlatArrayException", "classFlatArrayException.html", null ],
      [ "SGCore::SGNotImplementedException", "classSGCore_1_1SGNotImplementedException.html", null ]
    ] ],
    [ "SGCore::extract< Idx, Types >", "classSGCore_1_1extract.html", null ],
    [ "SGCore::FixedVector< T >", "structSGCore_1_1FixedVector.html", null ],
    [ "SGCore::FlagBase", "structSGCore_1_1FlagBase.html", null ],
    [ "flat_array< Elem, Dim, AllocationFlag >", "classflat__array.html", null ],
    [ "SGCore::FontGlyph", "structSGCore_1_1FontGlyph.html", null ],
    [ "SGCore::FontsManager", "structSGCore_1_1FontsManager.html", null ],
    [ "SGCore::FontSpecializationRenderer", "structSGCore_1_1FontSpecializationRenderer.html", null ],
    [ "SGCore::FontSpecializationSettings", "structSGCore_1_1FontSpecializationSettings.html", null ],
    [ "SGCore::FrameBufferAttachmentWithBlock", "structSGCore_1_1FrameBufferAttachmentWithBlock.html", null ],
    [ "Frustum", "classFrustum.html", null ],
    [ "SGCore::func_return_type< T >", "structSGCore_1_1func__return__type.html", null ],
    [ "SGCore::func_return_type< R(*)(Args...)>", "structSGCore_1_1func__return__type_3_01R_07_5_08_07Args_8_8_8_08_4.html", null ],
    [ "SGCore::func_return_type< R(Args...)>", "structSGCore_1_1func__return__type_3_01R_07Args_8_8_8_08_4.html", null ],
    [ "SGCore::func_return_type< R(C::*)(Args...) & >", "structSGCore_1_1func__return__type_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01_6_01_4.html", null ],
    [ "SGCore::func_return_type< R(C::*)(Args...) && >", "structSGCore_1_1func__return__type_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01_6_6_01_4.html", null ],
    [ "SGCore::func_return_type< R(C::*)(Args...) const & >", "structSGCore_1_1func__return__type_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01_6_01_4.html", null ],
    [ "SGCore::func_return_type< R(C::*)(Args...) const && >", "structSGCore_1_1func__return__type_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01_6_6_01_4.html", null ],
    [ "SGCore::func_return_type< R(C::*)(Args...) const >", "structSGCore_1_1func__return__type_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01_4.html", null ],
    [ "SGCore::func_return_type< R(C::*)(Args...) const volatile & >", "structSGCore_1_1func__return__type_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01volatile_01_6_01_4.html", null ],
    [ "SGCore::func_return_type< R(C::*)(Args...) const volatile && >", "structSGCore_1_1func__return__type_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01volatile_01_6_6_01_4.html", null ],
    [ "SGCore::func_return_type< R(C::*)(Args...) const volatile >", "structSGCore_1_1func__return__type_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01volatile_01_4.html", null ],
    [ "SGCore::func_return_type< R(C::*)(Args...) volatile & >", "structSGCore_1_1func__return__type_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01volatile_01_6_01_4.html", null ],
    [ "SGCore::func_return_type< R(C::*)(Args...) volatile && >", "structSGCore_1_1func__return__type_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01volatile_01_6_6_01_4.html", null ],
    [ "SGCore::func_return_type< R(C::*)(Args...) volatile >", "structSGCore_1_1func__return__type_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01volatile_01_4.html", null ],
    [ "SGCore::func_return_type< R(C::*)(Args...)>", "structSGCore_1_1func__return__type_3_01R_07C_1_1_5_08_07Args_8_8_8_08_4.html", null ],
    [ "get_address< RetT >", "structget__address.html", null ],
    [ "get_address< RetT(Args...)>", "structget__address_3_01RetT_07Args_8_8_8_08_4.html", null ],
    [ "SGCore::GizmoBase", "structSGCore_1_1GizmoBase.html", null ],
    [ "SGCore::MathUtils::GLMVectorHash< VecT >", "structSGCore_1_1MathUtils_1_1GLMVectorHash.html", null ],
    [ "SGCore::MathUtils::GLMVectorHash< glm::vec< N, T, Q > >", "structSGCore_1_1MathUtils_1_1GLMVectorHash_3_01glm_1_1vec_3_01N_00_01T_00_01Q_01_4_01_4.html", null ],
    [ "SGCore::GPUObject", "structSGCore_1_1GPUObject.html", [
      [ "SGCore::ISubPassShader", "classSGCore_1_1ISubPassShader.html", null ],
      [ "SGCore::ITexture2D", "classSGCore_1_1ITexture2D.html", null ]
    ] ],
    [ "SGCore::GPUObjectsStorage", "classSGCore_1_1GPUObjectsStorage.html", null ],
    [ "std::hash< SGCore::AABB< ScalarT > >", "structstd_1_1hash_3_01SGCore_1_1AABB_3_01ScalarT_01_4_01_4.html", null ],
    [ "std::hash< SGCore::FontSpecializationSettings >", "structstd_1_1hash_3_01SGCore_1_1FontSpecializationSettings_01_4.html", null ],
    [ "SGCore::HwExceptionHandler", "classSGCore_1_1HwExceptionHandler.html", null ],
    [ "SGCore::IAssetObserver", "classSGCore_1_1IAssetObserver.html", [
      [ "SGCore::IShader", "classSGCore_1_1IShader.html", null ]
    ] ],
    [ "SGCore::IFrameBufferAttachment", "structSGCore_1_1IFrameBufferAttachment.html", null ],
    [ "SGCore::IGeometryPass", "structSGCore_1_1IGeometryPass.html", [
      [ "SGCore::PBRRPGeometryPass", "structSGCore_1_1PBRRPGeometryPass.html", null ]
    ] ],
    [ "SGCore::IgnoreOctrees", "structSGCore_1_1IgnoreOctrees.html", null ],
    [ "SGCore::ImGuiWrap::ImGuiLayer", "structSGCore_1_1ImGuiWrap_1_1ImGuiLayer.html", null ],
    [ "SGCore::InputManager", "classSGCore_1_1InputManager.html", null ],
    [ "SGCore::IParallelSystemSubprocess< ParentParallelSystemT >", "structSGCore_1_1IParallelSystemSubprocess.html", null ],
    [ "SGCore::IParallelSystemSubprocess< OctreesSolver >", "structSGCore_1_1IParallelSystemSubprocess.html", [
      [ "SGCore::ObjectsCullingOctreesSolver", "structSGCore_1_1ObjectsCullingOctreesSolver.html", null ]
    ] ],
    [ "SGCore::IPlugin", "structSGCore_1_1IPlugin.html", null ],
    [ "SGCore::IRenderer", "classSGCore_1_1IRenderer.html", [
      [ "SGCore::GL4Renderer", "classSGCore_1_1GL4Renderer.html", [
        [ "SGCore::GL46Renderer", "classSGCore_1_1GL46Renderer.html", null ]
      ] ],
      [ "SGCore::VkRenderer", "classSGCore_1_1VkRenderer.html", null ]
    ] ],
    [ "SGCore::IRenderPass", "structSGCore_1_1IRenderPass.html", [
      [ "SGCore::PBRRPDirectionalLightsPass", "structSGCore_1_1PBRRPDirectionalLightsPass.html", null ],
      [ "SGCore::PBRRPGeometryPass", "structSGCore_1_1PBRRPGeometryPass.html", null ],
      [ "SGCore::PostProcessPass", "structSGCore_1_1PostProcessPass.html", null ],
      [ "SGCore::TextRenderPass", "structSGCore_1_1TextRenderPass.html", null ]
    ] ],
    [ "SGCore::IShaderUniform", "structSGCore_1_1IShaderUniform.html", null ],
    [ "SGCore::ISystem", "classSGCore_1_1ISystem.html", [
      [ "SGCore::IParallelSystem< PhysicsWorld3D >", "classSGCore_1_1IParallelSystem.html", null ],
      [ "SGCore::IParallelSystem< TransformationsUpdater >", "classSGCore_1_1IParallelSystem.html", null ],
      [ "SGCore::IParallelSystem< OctreesSolver >", "classSGCore_1_1IParallelSystem.html", null ],
      [ "SGCore::AtmosphereUpdater", "structSGCore_1_1AtmosphereUpdater.html", null ],
      [ "SGCore::AudioProcessor", "structSGCore_1_1AudioProcessor.html", null ],
      [ "SGCore::BatchesRenderer", "structSGCore_1_1BatchesRenderer.html", null ],
      [ "SGCore::BoxGizmosRenderer", "classSGCore_1_1BoxGizmosRenderer.html", null ],
      [ "SGCore::Controllables3DUpdater", "structSGCore_1_1Controllables3DUpdater.html", null ],
      [ "SGCore::DebugDraw", "classSGCore_1_1DebugDraw.html", null ],
      [ "SGCore::DirectionalLightsUpdater", "structSGCore_1_1DirectionalLightsUpdater.html", null ],
      [ "SGCore::IParallelSystem< ParallelSystemT >", "classSGCore_1_1IParallelSystem.html", null ],
      [ "SGCore::LineGizmosRenderer", "structSGCore_1_1LineGizmosRenderer.html", null ],
      [ "SGCore::RenderingBasesUpdater", "structSGCore_1_1RenderingBasesUpdater.html", null ],
      [ "SGCore::SphereGizmosUpdater", "structSGCore_1_1SphereGizmosUpdater.html", null ]
    ] ],
    [ "IteratorClass< Element, direction >", "classIteratorClass.html", null ],
    [ "SGCore::IVertexAttribute", "classSGCore_1_1IVertexAttribute.html", [
      [ "SGCore::GLVertexAttribute", "structSGCore_1_1GLVertexAttribute.html", null ],
      [ "SGCore::VkVertexAttribute", "classSGCore_1_1VkVertexAttribute.html", null ]
    ] ],
    [ "SGCore::Layer", "structSGCore_1_1Layer.html", null ],
    [ "SGCore::LayeredFrameReceiver", "classSGCore_1_1LayeredFrameReceiver.html", null ],
    [ "SGCore::LightBase", "structSGCore_1_1LightBase.html", null ],
    [ "SGCore::LineGizmo", "structSGCore_1_1LineGizmo.html", null ],
    [ "SGCore::make_noexcept< T, noexcept_state >", "structSGCore_1_1make__noexcept.html", null ],
    [ "SGCore::make_noexcept< R(Args...) &&, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_08_01_6_6_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...) &&noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_08_01_6_6noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...) &noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_08_01_6noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...) const &&, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_08_01const_01_6_6_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...) const &&noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_08_01const_01_6_6noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...) const &, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_08_01const_01_6_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...) const &noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_08_01const_01_6noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...) const noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_08_01const_01noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...) const volatile &&, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_08_01const_01volatile_01_6_6_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...) const volatile &&noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_08_01const_01volatile_01_6_6noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...) const volatile &, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_08_01const_01volatile_01_6_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...) const volatile &noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_08_01const_01volatile_01_6noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...) const volatile noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_08_01const_01volatile_01noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...) const volatile, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_08_01const_01volatile_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...) const, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_08_01const_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...) noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_08_01noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...) volatile &&, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_08_01volatile_01_6_6_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...) volatile &&noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_08_01volatile_01_6_6noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...) volatile &, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_08_01volatile_01_6_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...) volatile &noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_08_01volatile_01_6noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...) volatile noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_08_01volatile_01noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...) volatile, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_08_01volatile_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...)&, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_08_6_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...), noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_08_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...,...) &&, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_00_8_8_8_08_01_6_6_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...,...) &&noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_00_8_8_8_08_01_6_6noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...,...) &noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_00_8_8_8_08_01_6noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...,...) const &&, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_00_8_8_8_08_01const_01_6_6_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...,...) const &&noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_00_8_8_8_08_01const_01_6_6noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...,...) const &, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_00_8_8_8_08_01const_01_6_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...,...) const &noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_00_8_8_8_08_01const_01_6noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...,...) const noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_00_8_8_8_08_01const_01noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...,...) const volatile &&, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_00_8_8_8_08_01const_01volatile_01_6_6_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...,...) const volatile &&noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_00_8_8_8_08_01const_01volatile_01_6_6noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...,...) const volatile &, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_00_8_8_8_08_01const_01volatile_01_6_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...,...) const volatile &noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_00_8_8_8_08_01const_01volatile_01_6noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...,...) const volatile noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_00_8_8_8_08_01const_01volatile_01noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...,...) const volatile, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_00_8_8_8_08_01const_01volatile_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...,...) const, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_00_8_8_8_08_01const_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...,...) noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_00_8_8_8_08_01noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...,...) volatile &&, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_00_8_8_8_08_01volatile_01_6_6_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...,...) volatile &&noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_00_8_8_8_08_01volatile_01_6_6noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...,...) volatile &, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_00_8_8_8_08_01volatile_01_6_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...,...) volatile &noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_00_8_8_8_08_01volatile_01_6noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...,...) volatile noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_00_8_8_8_08_01volatile_01noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...,...) volatile, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_00_8_8_8_08_01volatile_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...,...)&, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_00_8_8_8_08_6_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(Args...,...), noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07Args_8_8_8_00_8_8_8_08_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...) &&, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01_6_6_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...) &&noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01_6_6noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...) &noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01_6noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...) const &&, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01_6_6_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...) const &&noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01_6_6noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...) const &, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01_6_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...) const &noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01_6noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...) const noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...) const volatile &&, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01volatile_01_6_6_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...) const volatile &&noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01volatile_01_6_6noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...) const volatile &, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01volatile_01_6_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...) const volatile &noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01volatile_01_6noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...) const volatile noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01volatile_01noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...) const volatile, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01volatile_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...) const, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...) noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...) volatile &&, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01volatile_01_6_6_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...) volatile &&noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01volatile_01_6_6noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...) volatile &, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01volatile_01_6_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...) volatile &noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01volatile_01_6noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...) volatile noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01volatile_01noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...) volatile, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01volatile_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...)&, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_08_6_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...), noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_08_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...,...) &&, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_00_8_8_8_08_01_6_6_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...,...) &&noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_00_8_8_8_08_01_6_6noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...,...) &noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_00_8_8_8_08_01_6noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...,...) const &&, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_00_8_8_8_08_01const_01_6_6_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...,...) const &&noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_00_8_8_8_08_01const_01_6_6noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...,...) const &, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_00_8_8_8_08_01const_01_6_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...,...) const &noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_00_8_8_8_08_01const_01_6noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...,...) const noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_00_8_8_8_08_01const_01noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...,...) const volatile &&, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_00_8_8_8_08_01const_01volatile_01_6_6_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...,...) const volatile &&noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_00_8_8_8_08_01const_01volatile_014840af0374caec663e8e34959e56042e.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...,...) const volatile &, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_00_8_8_8_08_01const_01volatile_01_6_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...,...) const volatile &noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_00_8_8_8_08_01const_01volatile_0105b57a9d96d3d488e80d4df2a3cef3a8.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...,...) const volatile noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_00_8_8_8_08_01const_01volatile_01f1481c8e804887d450d58fb31b71e9d0.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...,...) const volatile, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_00_8_8_8_08_01const_01volatile_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...,...) const, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_00_8_8_8_08_01const_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...,...) noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_00_8_8_8_08_01noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...,...) volatile &&, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_00_8_8_8_08_01volatile_01_6_6_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...,...) volatile &&noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_00_8_8_8_08_01volatile_01_6_6noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...,...) volatile &, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_00_8_8_8_08_01volatile_01_6_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...,...) volatile &noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_00_8_8_8_08_01volatile_01_6noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...,...) volatile noexcept, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_00_8_8_8_08_01volatile_01noexcept_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...,...) volatile, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_00_8_8_8_08_01volatile_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...,...)&, noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_00_8_8_8_08_6_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::make_noexcept< R(C::*)(Args...,...), noexcept_state >", "structSGCore_1_1make__noexcept_3_01R_07C_1_1_5_08_07Args_8_8_8_00_8_8_8_08_00_01noexcept__state_01_4.html", null ],
    [ "SGCore::MathUtils", "structSGCore_1_1MathUtils.html", null ],
    [ "SGCore::Mesh", "structSGCore_1_1Mesh.html", null ],
    [ "SGCore::MeshBase", "structSGCore_1_1MeshBase.html", null ],
    [ "SGCore::MeshBuilder", "structSGCore_1_1MeshBuilder.html", null ],
    [ "SGCore::MeshDataRenderInfo", "structSGCore_1_1MeshDataRenderInfo.html", null ],
    [ "SGCore::Node", "classSGCore_1_1Node.html", null ],
    [ "SGCore::ObjectsCullingOctree", "structSGCore_1_1ObjectsCullingOctree.html", null ],
    [ "SGCore::Octree", "structSGCore_1_1Octree.html", null ],
    [ "SGCore::OctreeCullable", "structSGCore_1_1OctreeCullable.html", null ],
    [ "SGCore::OctreeNode", "structSGCore_1_1OctreeNode.html", null ],
    [ "SGCore::PluginsManager", "structSGCore_1_1PluginsManager.html", null ],
    [ "SGCore::PluginWrap", "structSGCore_1_1PluginWrap.html", null ],
    [ "SGCore::pointer_type", "structSGCore_1_1pointer__type.html", null ],
    [ "SGCore::PostProcessEffect", "structSGCore_1_1PostProcessEffect.html", [
      [ "SGCore::SSAO", "structSGCore_1_1SSAO.html", null ]
    ] ],
    [ "SGCore::PostProcessFXSubPass", "structSGCore_1_1PostProcessFXSubPass.html", null ],
    [ "SGUtils::Utils::RawPointerHash< T >", "structSGUtils_1_1Utils_1_1RawPointerHash.html", null ],
    [ "SGCore::reference_type", "structSGCore_1_1reference__type.html", null ],
    [ "SGCore::RenderingBase", "structSGCore_1_1RenderingBase.html", null ],
    [ "SGCore::RenderPipelinesManager", "structSGCore_1_1RenderPipelinesManager.html", null ],
    [ "SGCore::repeated_type< T, RepeatsCnt >", "structSGCore_1_1repeated__type.html", null ],
    [ "reverse_wrapper< T >", "structreverse__wrapper.html", null ],
    [ "SGCore::Rigidbody3D", "structSGCore_1_1Rigidbody3D.html", null ],
    [ "SGCore::SafeObject< ObjT >", "structSGCore_1_1SafeObject.html", null ],
    [ "SGCore::SafeObject< std::vector< entity_t > >", "structSGCore_1_1SafeObject.html", null ],
    [ "SGCore::SafeObject< std::vector< SGCore::EntityComponentMember< glm::mat4 > > >", "structSGCore_1_1SafeObject.html", null ],
    [ "SGCore::SafeObject< std::vector< SGCore::EntityComponentMember< Ref< const SGCore::Transform > > > >", "structSGCore_1_1SafeObject.html", null ],
    [ "SGCore::Server", "classSGCore_1_1Server.html", null ],
    [ "SGCore::SGSLEAssignExpression", "structSGCore_1_1SGSLEAssignExpression.html", null ],
    [ "SGCore::SGSLEBracketsListener", "structSGCore_1_1SGSLEBracketsListener.html", [
      [ "SGCore::SGSLESubPass", "structSGCore_1_1SGSLESubPass.html", null ],
      [ "SGCore::SGSLESubShader", "structSGCore_1_1SGSLESubShader.html", null ]
    ] ],
    [ "SGCore::SGSLEStruct", "structSGCore_1_1SGSLEStruct.html", null ],
    [ "SGCore::SGSLETranslator", "classSGCore_1_1SGSLETranslator.html", null ],
    [ "SGCore::SGSLETranslatorConfiguration", "structSGCore_1_1SGSLETranslatorConfiguration.html", null ],
    [ "SGCore::SGSLEVariable", "structSGCore_1_1SGSLEVariable.html", null ],
    [ "SGCore::ShaderComponent", "structSGCore_1_1ShaderComponent.html", null ],
    [ "SGCore::ShaderDefine", "structSGCore_1_1ShaderDefine.html", null ],
    [ "SGCore::ShadersPaths", "structSGCore_1_1ShadersPaths.html", null ],
    [ "SGCore::ShadersUtils", "structSGCore_1_1ShadersUtils.html", null ],
    [ "SGCore::ShaderTextureBinding", "structSGCore_1_1ShaderTextureBinding.html", null ],
    [ "SGCore::SimpleFrameReceiver", "structSGCore_1_1SimpleFrameReceiver.html", null ],
    [ "SGUtils::Singleton", "structSGUtils_1_1Singleton.html", null ],
    [ "SGCore::SphereGizmo", "structSGCore_1_1SphereGizmo.html", null ],
    [ "SGCore::STBITextureDataDeleter", "structSGCore_1_1STBITextureDataDeleter.html", null ],
    [ "SGCore::Style", "structSGCore_1_1Style.html", null ],
    [ "SGCore::StylesManager", "structSGCore_1_1StylesManager.html", null ],
    [ "SGCore::Threading::TaskSingletonGuardImpl", "structSGCore_1_1Threading_1_1TaskSingletonGuardImpl.html", null ],
    [ "SGCore::Text", "structSGCore_1_1Text.html", null ],
    [ "SGCore::Threading::ThreadsManager", "structSGCore_1_1Threading_1_1ThreadsManager.html", null ],
    [ "SGCore::Threading::ThreadsPool", "structSGCore_1_1Threading_1_1ThreadsPool.html", null ],
    [ "SGCore::Timer", "classSGCore_1_1Timer.html", null ],
    [ "SGCore::TimerCallback", "classSGCore_1_1TimerCallback.html", null ],
    [ "SGCore::Transform", "structSGCore_1_1Transform.html", null ],
    [ "SGCore::TransformBase", "structSGCore_1_1TransformBase.html", null ],
    [ "SGCore::Type< T >", "structSGCore_1_1Type.html", null ],
    [ "SGCore::TypesCounter", "structSGCore_1_1TypesCounter.html", null ],
    [ "SGUtils::Utils::TypeWrapper< T >", "structSGUtils_1_1Utils_1_1TypeWrapper.html", null ],
    [ "SGCore::UICamera", "classSGCore_1_1UICamera.html", null ],
    [ "SGCore::UIElement", "structSGCore_1_1UIElement.html", null ],
    [ "SGCore::UniqueName", "structSGCore_1_1UniqueName.html", null ],
    [ "SGCore::UniqueNamesCounter", "classSGCore_1_1UniqueNamesCounter.html", null ],
    [ "SGCore::UniqueNameWrapper", "classSGCore_1_1UniqueNameWrapper.html", [
      [ "SGCore::EntityBaseInfo", "structSGCore_1_1EntityBaseInfo.html", null ],
      [ "SGCore::IAsset", "classSGCore_1_1IAsset.html", [
        [ "SGCore::ByteFileAsset", "structSGCore_1_1ByteFileAsset.html", [
          [ "SGCore::AudioTrackAsset", "structSGCore_1_1AudioTrackAsset.html", null ]
        ] ],
        [ "SGCore::Font", "structSGCore_1_1Font.html", null ],
        [ "SGCore::IMaterial", "classSGCore_1_1IMaterial.html", null ],
        [ "SGCore::ITexture2D", "classSGCore_1_1ITexture2D.html", null ],
        [ "SGCore::ModelAsset", "classSGCore_1_1ModelAsset.html", null ],
        [ "SGCore::ShaderAnalyzedFile", "structSGCore_1_1ShaderAnalyzedFile.html", null ],
        [ "SGCore::ShaderFileAsset", "structSGCore_1_1ShaderFileAsset.html", null ],
        [ "SGCore::TextFileAsset", "structSGCore_1_1TextFileAsset.html", null ],
        [ "SGCore::XMLDocument", "structSGCore_1_1XMLDocument.html", null ]
      ] ],
      [ "SGCore::IFrameBuffer", "classSGCore_1_1IFrameBuffer.html", null ],
      [ "SGCore::ISubPassShader", "classSGCore_1_1ISubPassShader.html", null ]
    ] ],
    [ "SGCore::unknown_type", "structSGCore_1_1unknown__type.html", null ],
    [ "SGUtils::Utils", "structSGUtils_1_1Utils.html", null ],
    [ "SGUtils::UUID", "structSGUtils_1_1UUID.html", null ],
    [ "SGUtils::Utils::WeakCompare< T >", "structSGUtils_1_1Utils_1_1WeakCompare.html", null ],
    [ "SGUtils::Utils::WeakPointerHash< T >", "structSGUtils_1_1Utils_1_1WeakPointerHash.html", null ],
    [ "SGCore::Window", "structSGCore_1_1Window.html", null ],
    [ "SGCore::WindowConfig", "classSGCore_1_1WindowConfig.html", null ]
];