#ifdef SG_INSTANCED_RENDERING
    layout (location = 0) in mat4 SG_INSTANCED_instanceModelMatrix;
    layout (location = 4) in vec4 SG_INSTANCED_instancePosition;
    layout (location = 5) in vec4 SG_INSTANCED_instanceRotation;
    layout (location = 6) in vec4 SG_INSTANCED_instanceScale;

    #define SG_VS_POSITIONS_ATTRIBUTE_LOC 7
    #define SG_VS_UV_ATTRIBUTE_LOC 8
    #define SG_VS_NORMALS_ATTRIBUTE_LOC 9
    #define SG_VS_TANGENTS_ATTRIBUTE_LOC 10
    #define SG_VS_BITANGENTS_ATTRIBUTE_LOC 11
    #define SG_VS_BONES_IDS_ATTRIBUTE0_LOC 12
    #define SG_VS_BONES_IDS_ATTRIBUTE1_LOC 13
    #define SG_VS_BONES_WEIGHTS_ATTRIBUTE0_LOC 14
    #define SG_VS_BONES_WEIGHTS_ATTRIBUTE1_LOC 15
    #define SG_VS_VERTEX_COLOR_ATTRIBUTE0_LOC 16
    #define SG_VS_VERTEX_COLOR_ATTRIBUTE1_LOC 17
    #define SG_VS_VERTEX_COLOR_ATTRIBUTE2_LOC 18
    #define SG_VS_VERTEX_COLOR_ATTRIBUTE3_LOC 19
    #define SG_VS_VERTEX_COLOR_ATTRIBUTE4_LOC 20
    #define SG_VS_VERTEX_COLOR_ATTRIBUTE5_LOC 21
    #define SG_VS_VERTEX_COLOR_ATTRIBUTE6_LOC 22
    #define SG_VS_VERTEX_COLOR_ATTRIBUTE7_LOC 23
#else
    #define SG_VS_POSITIONS_ATTRIBUTE_LOC 0
    #define SG_VS_UV_ATTRIBUTE_LOC 1
    #define SG_VS_NORMALS_ATTRIBUTE_LOC 2
    #define SG_VS_TANGENTS_ATTRIBUTE_LOC 3
    #define SG_VS_BITANGENTS_ATTRIBUTE_LOC 4
    #define SG_VS_BONES_IDS_ATTRIBUTE0_LOC 5
    #define SG_VS_BONES_IDS_ATTRIBUTE1_LOC 6
    #define SG_VS_BONES_WEIGHTS_ATTRIBUTE0_LOC 7
    #define SG_VS_BONES_WEIGHTS_ATTRIBUTE1_LOC 8
    #define SG_VS_VERTEX_COLOR_ATTRIBUTE0_LOC 9
    #define SG_VS_VERTEX_COLOR_ATTRIBUTE1_LOC 10
    #define SG_VS_VERTEX_COLOR_ATTRIBUTE2_LOC 11
    #define SG_VS_VERTEX_COLOR_ATTRIBUTE3_LOC 12
    #define SG_VS_VERTEX_COLOR_ATTRIBUTE4_LOC 13
    #define SG_VS_VERTEX_COLOR_ATTRIBUTE5_LOC 14
    #define SG_VS_VERTEX_COLOR_ATTRIBUTE6_LOC 15
    #define SG_VS_VERTEX_COLOR_ATTRIBUTE7_LOC 16
#endif