/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pixelfield_sungearstarter_NativeMethods */

#ifndef _Included_com_pixelfield_sungearstarter_NativeMethods
#define _Included_com_pixelfield_sungearstarter_NativeMethods
#ifdef __cplusplus
extern "C" {
#endif
  /*
   * Class:     com_pixelfield_sungearstarter_NativeMethods
   * Method:    startSGCore
   * Signature: ()V
   */
  JNIEXPORT void JNICALL Java_com_pixelfield_sungearstarter_NativeMethods_startSGCore(JNIEnv* env, jclass clazz, jobject context);

#ifdef __cplusplus
}
#endif
#endif
