/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class com_pixelfield_sungearstarter_NativeMethods */

#ifndef _Included_com_pixelfield_sungearstarter_NativeMethods
#define _Included_com_pixelfield_sungearstarter_NativeMethods

#include <jni.h>

#include "SGCore/Utils/Platform.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef SG_PLATFORM_OS_ANDROID
  /*
   * Class:     com_pixelfield_sungearstarter_NativeMethods
   * Method:    startSGCore
   * Signature: ()V
   */
  JNIEXPORT void JNICALL Java_com_pixelfield_sungearstarter_NativeMethods_startSGCore(JNIEnv* env, jclass thisClass, jobject context, jobject surface);

#endif

#ifdef __cplusplus
}

#ifdef SG_PLATFORM_OS_ANDROID
#include <android/native_window.h>

namespace SGCore::__AndroidImpl
{
  void setAndroidMainWindowHandle(ANativeWindow* window) noexcept;
}

#endif

#endif
#endif
